# Generated by Django 5.0.6 on 2024-05-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_attendancerecord_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data', models.DateTimeField(auto_now=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('accept', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
