# Generated by Django 5.0.6 on 2024-05-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_studnotifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studnotifications',
            name='data',
        ),
    ]
